runtime: python311
service: elicita-backend  # all lowercase

instance_class: F2

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  APP_ENV: "prod"

  DB_USER: "appsadmin"
  DB_PWD: "appsadmin2025"
  DB_NAME: "Elicita_V2"
  INSTANCE_CONNECTION_NAME: "theta-messenger-459613-p7:asia-south1:appsadmin"

  SECRET_KEY: "change-this-in-prod"
  FRONTEND_ORIGINS: "https://your-frontend-domain.com"

beta_settings:
  cloud_sql_instances: "theta-messenger-459613-p7:asia-south1:appsadmin"

handlers:
  - url: /.*
    script: auto
