runtime: python311
service: elicita-backend   # all lowercase, no spaces

instance_class: F2         # or F1; change if you need more power

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  APP_ENV: "prod"

  # DB credentials (same as you use now)
  DB_USER: "appsadmin"
  DB_PWD: "appsadmin2025"
  DB_NAME: "Elicita_V2"

  # Cloud SQL instance (from your screenshot)
  INSTANCE_CONNECTION_NAME: "theta-messenger-459613-p7:asia-south1:appsadmin"

  # Session / CORS
  SECRET_KEY: "change-this-in-prod"
  FRONTEND_ORIGINS: "https://your-frontend-domain.com"

  # Optional – only if you really use a custom cookie domain
  # SESSION_COOKIE_DOMAIN: ".datasolve-analytics.net"

beta_settings:
  # This mounts the Unix domain socket at /cloudsql/INSTANCE_CONNECTION_NAME
  cloud_sql_instances: "theta-messenger-459613-p7:asia-south1:appsadmin"

handlers:
  - url: /.*
    script: auto
