runtime: python312
env: standard
# gunicorn will call your factory function
entrypoint: gunicorn -b :$PORT app:create_app()
instance_class: F2
handlers:
  - url: /.*
    script: auto
# scale settings (tune as you like)
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
inbound_services:
  - warmup
env_variables:
  # ---- app mode & session/cookie ----
  APP_ENV: "prod"
  FRONTEND_ORIGINS: "https://logsy.datasolve-analytics.net"
  SESSION_COOKIE_DOMAIN: ".datasolve-analytics.net"
  SECRET_KEY: "change_this_in_prod"
  # ---- MySQL (hosted in theta-messenger-459613-p7) ----
  DB_USER: "appsadmin"
  DB_PWD: "appsadmin2025"
  DB_HOST: "34.93.75.171"
  DB_NAME: "Elicita_V2"







